<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>consulat-termine-ui-2025</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConsulatTermine.Application\ConsulatTermine.Application.csproj" />
    <ProjectReference Include="..\ConsulatTermine.Infrastructure\ConsulatTermine.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Blazored.SessionStorage" />
  </ItemGroup>

</Project>
